### ISSUE TITLE
Pages that bring project over 8 measures get set to one measure

### ISSUE THREAD

**Issue by DumbGameMaker** [OpenMarch/OpenMarch#184]
I have a project with the following structure:

- 4
- 4
- 8
- 4
- 8
- 16

Upon creating the last set, it gets created as 4 counts instead of 16. Creating pages after that get their length set properly.

**Comment by AlexDumo** [comment]
Thanks for submitting! This is odd, I'll check it out tomorrow

**Comment by AlexDumo** [comment]
I've reproduced the issue. It looks like the problem is coming from your last page being a smaller amount of counts than the last measure. Here's a couple examples of the same bug that you're encountering

Pages: 4-4-8-4-7-16 (which actually displays as 9)
<img width="890" alt="image" src="https://github.com/user-attachments/assets/c85727bf-d920-4176-9970-2231020045ce">

as I change the length of the last measure, the page adjusts to fit it (after a refresh [ctrl+R]). In this case, the following page (pg. 8) gets cut off to 2 counts even though it should be 8
<img width="1054" alt="image" src="https://github.com/user-attachments/assets/be170534-995d-49b5-a76c-0e271d262aa8">

The pages are being stored in the database correctly, but they're being treated in the front-end as though they are shorter. I'll try and fix this soon. Thanks for reporting!
