### ISSUE TITLE
Mac Users

### ISSUE THREAD

**Issue by FarmcardMitch** [OpenMarch/OpenMarch#265]
I've download for Mac, but it says it has to be updated and won't run.  What should I do?

**Comment by AlexDumo** [comment]
So many people have asked this that we should put it on the website :)

## Installing on MacOS
You may run into trouble due to some code signing steps I need to do. It should be fixed by the end of the month. We have lots of things we need to do to make sure Apple knows we're not malware.

In the meantime you can force MacOS to open it by doing the following:
1. Open the app, see validation error. 
1. Next open system settings and navigate to Security & Privacy. 
1. Scroll down under security and you will see a selection that says "open anyway".

More detailed instructions can be found here: https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unknown-developer-mh40616/mac

You can always ask for help in our [community Discord](https://discord.gg/eTsQ98uZzq) Thank you for using OpenMarch!
